### ISSUE TITLE
Digit markers

### ISSUE THREAD

**Issue by Jcastanyo** [vocdex/digit-depth#2]
Hi! My name is Julio, 

I am working with Digit sensors and I would like to ask you about the digit markers. How did you make the markers over the gel surface?

Thanks in advance.

**Comment by vocdex** [comment]
Hi, Julio!
Thanks for reaching out. As far as I know, there are two ways to paint the markers:
1. Use a laser cutter&engraving machine to engrave arrays of dots on top of white DIGIT gel. Since these dots are transparent now, you have to paint it with black. Make sure to apply the black paint gently with the sprayer.
2. Use water [transfer paper](https://www.amazon.com/Waterslide-Transfer-Transparent-Printable-Tumblers/dp/B098KYH7R9/ref=sr_1_3?keywords=lazertran+inkjet+transfer+paper&qid=1670052053&sr=8-3) on top of transparent gel and paint with white and/or black.
We have only used method 1 and it is sufficient for our purposes. Here's what it looks like on our 3D printed DIGIT:
![0020](https://user-images.githubusercontent.com/19290583/205430004-531a52ac-d8ad-4d90-b0f7-cae1073b608c.png)

Let me know if you have more questions.

**Comment by Jcastanyo** [comment]
Thank you very much for your answer! 
In the first method, after making the dots, is It posible to paint with a paintbrush? 
In the second method, how do you paint the dots on the paper?

**Comment by vocdex** [comment]
1. I haven't tried painting with a paint brush but as long as the black paint blocks the light passing through transparent markers, it should be fine. 
2. You can print the dots on transfer paper. I am not sure about the details but the process is similar to how a transfer paper is used in general: [Example](https://www.youtube.com/watch?v=Io-gaaFujTM).

**Comment by Jcastanyo** [comment]
Thank you very much!!!
